name: prepare fork

on:
  workflow_dispatch:

jobs:
  get-metadata:
    name: Get Metadata
    runs-on: ubuntu-latest
    outputs:
      latest_tag: ${{ steps.get_latest_tag.outputs.tag }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Latest Tag
        id: get_latest_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: main
  prepare-demo:
    needs: get-metadata
    uses: ./.github/workflows/prepare-demo.yml
    with:
      source_ref: ${{ needs.get-metadata.outputs.latest_tag }}
      branchname: demo
      user1_name: User One
      user1_email: userone@example.com
      user2_name: User Two
      user2_email: usertwo@example.com
  # change-default-branch:
  #   runs-on: ubuntu-latest
  #   needs: prepare-demo
  #   steps:
  #     - uses: octokit/request-action@v2.x
  #       id: change_defaut_branch
  #       with:
  #         route: PATCH /repos/{repo}
  #         repo: ${{ github.repository }}
  #         default_branch: demo
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-images:
    needs: prepare-demo
    uses:
      ./.github/workflows/build-push-image.yml
    with:
      ref_name: demo